-- Missing dimensions patch for prod
-- Generated: 2026-08-04T20:05:08.894Z
-- Targets 211 prod products that have no dimensions

UPDATE products SET dimensions='Height: 73,00 cm; Length: 170,00 cm; Width: 85,00 cm', materials='Tabletop in plywood with lacquered oak veneer surface, Black and Grey version in plywood with linoleum surface, White version in plywood with laminate surface (HPL). Solid Oak and Solid Smoked Oak tabletop in FSC™-certified (FSC-C028824) oak. Frame in powder-coated aluminum.  Oak veneer: slight color variations can occur due to the material''s inherent characteristics.  Powder Coated Aluminum: Aluminum''s malleability makes it a grand fit for highly detailed, durable Muuto products, bringing a lig' WHERE name='70/70 Table';
UPDATE products SET dimensions='Height: 37,40 cm; Length: 38,50 cm; Width: 44,00 cm', materials='The tabletop is made from plywood with either a nanolaminate or clear lacquered oak veneer finish. The frame is made from 8mm powder-coated solid steel.  Powder-Coated Steel: Steel is an alloy of iron with carbon. Powder-coated steel has a subtle, textured expression and elegant feel while adding durability to the design and making it more corrosion-resistant. Powder-coated steel is also highly chip-resistant.  Nanolaminate: Nanolaminate is a fully dense, ultra-fine-grained solid with a high con' WHERE name='Airy Coffee Table';
UPDATE products SET dimensions='Height: 9,80 cm; Length: 16,70 cm; Width: 16,70 cm; Diameter: 16,70 cm; Cord length: 400,00 cm', materials='The lampshade is made from press-spun aluminum. Colored versions are polished and wet-painted, while the Brushed Aluminum version is brushed and lacquered. The cord is made from extruded PVC, and the canopy is made from injection-molded ABS. The Brushed Aluminum EU version is designed for disassembly. The lamp is produced without intentionally added PFAS.' WHERE name='Ambit Pendant Lamp White - Ø 55 cm';
UPDATE products SET dimensions='Height: 19,70 cm; Width: 126,00 cm; Depth: 25,00 cm; Diameter: 25,00 cm; Cord length: 400,00 cm', materials='Rail made from cast and extruded aluminum. Shades in spun aluminum with a rubber cord and steel wires. Made from old brazier traditions, the lampshades are press spun by hand. Hereafter, the lampshades are polished and painted by hand. The rail is cut from tubes that are adjusted to fit each other on a lathe machine.' WHERE name='Ambit Rail Lamp White';
UPDATE products SET dimensions='Height: 19,50 cm; Length: 40,70 cm; Width: 16,70 cm; Cord length: 250,00 cm', materials='The lampshade, arm fixture, and wall mount piece are made from aluminum and wet painted. The cord is made from PVC. An extra wall bracket is included in the Ambit Wall Lamp.' WHERE name='Ambit Wall Lamp White';
UPDATE products SET dimensions='Height: 80,00 cm; Width: 55,00 cm; Depth: 5,10 cm', materials='Frame made from FSC™-certified (FSC-C028824) spruce wood. Clear mirror glass. The spruce wood frame is treated with a wood stain color and finished with a clear oil. For the natural spruce variant, the frame is treated with a white pigmented oil. A black backboard encloses the mirror.' WHERE name='Arced Mirror';
UPDATE products SET dimensions='Height: 46,00 cm; Diameter: 45,00 cm', materials='Oak and Ash versions are made from oak or ash plywood and solid oak or ash legs with water-based lacquer. Colored versions are made from MDF or ash plywood and solid ash legs in water-based lacquer. All versions are made using FSC™-certified (FSC-C028824) wood.  Oak and ash veneer: slight color variations can occur due to the inherent characteristics of the material.' WHERE name='Around Coffee Table';
UPDATE products SET dimensions='Height: 45,00 cm; Width: 180,00 cm; Depth: 36,40 cm; Seat height: 45,00 cm; Seat depth: 36,40 cm', materials='Made using FSC™-certified (FSC-C028824) teak. Teak is a durable hardwood well-suited for outdoor use. As a natural material, teak will display variations in color and grain from one piece to another. When left untreated, the wood will gradually develop a silver-grey patina. Over time, outdoor exposure may also lead to small cracks at the ends of the planks and slight warping, which can result in minor height differences between them. Direct sunlight may cause temporary color variations if object' WHERE name='Assemble Bench';
UPDATE products SET dimensions='Height: 36,00 cm; Length: 55,00 cm; Width: 55,00 cm; Seat height: 28,80 cm', materials='Made using FSC™-certified (FSC-C028824) teak. Teak is a durable hardwood well-suited for outdoor use. As a natural material, teak will display variations in color and grain from one piece to another. When left untreated, the wood will gradually develop a silver-grey patina. Over time, outdoor exposure may also lead to small cracks at the ends of the planks and slight warping, which can result in minor height differences between them. Direct sunlight may cause temporary color variations if object' WHERE name='Assemble Coffee Table';
UPDATE products SET dimensions='Height: 73,00 cm; Length: 220,00 cm; Width: 92,20 cm; Seat height: 62,80 cm', materials='Made using FSC™-certified (FSC-C028824) teak. Teak is a durable hardwood well-suited for outdoor use. As a natural material, teak will display variations in color and grain from one piece to another. When left untreated, the wood will gradually develop a silver-grey patina. Over time, outdoor exposure may also lead to small cracks at the ends of the planks and slight warping, which can result in minor height differences between them. Direct sunlight may cause temporary color variations if object' WHERE name='Assemble Table';
UPDATE products SET dimensions='Height: 6,3 cm; Width: 2,1 cm; Depth: 5,1 cm', materials='Product Material                                              The Attach Coat Hook is made from oak and aluminum, colored with PVD vacuum-treated surface.' WHERE name='Attach Coat Hook Set of 2';
UPDATE products SET dimensions='Height: 7,00 cm; Length: 87,50 cm; Width: 3,80 cm', materials='Rack and dots in FSC™-certified (FSC-C028824) oak that is either oiled or lacquered. Hooks in powder-coated steel.' WHERE name='Avail Coat Rack';
UPDATE products SET dimensions='Height: 73,00 cm; Diameter: 110,00 cm', materials='The tabletop is made of plywood with either laminate, linoleum, or oak veneer surface and a water-based lacquer. Plywood or ABS edges. Frame and legs in powder-coated aluminum.  Oak Veneer: Slight color variations may reflect the material''s natural characteristics.  Powder-Coated Aluminum: Aluminum''s malleability makes it ideal for intricate, durable designs, offering a light, airy touch to robust constructions.  Laminate: The laminate used in our designs is partly made from melamine resin, one ' WHERE name='Base Round Table';
UPDATE products SET dimensions='Length: 90 cm; Height: 73 cm; Width: 90 cm; Diameter: 90 cm', materials='Product Material                                              The tabletop is made of plywood with either laminate, linoleum, or oak veneer surface and a water-based lacquer. Plywood or ABS edges. Frame and legs in powder-coated aluminum.Oak Veneer: Slight color variations may reflect the material''s natural characteristics.Powder-Coated Aluminum: Aluminum''s malleability makes it ideal for intricate, durable designs, offering a light, airy touch to robust constructions.Laminate: The laminate used' WHERE name='Base Round Table With Castors';
UPDATE products SET dimensions='Height: 73,00 cm; Length: 140,00 cm; Width: 80,00 cm; Depth: 80,00 cm', materials='The tabletop is made of plywood with either laminate, linoleum, or oak veneer surface and a water-based lacquer. Plywood or ABS edges. Frame and legs in powder-coated aluminum.  Oak Veneer: Slight color variations may reflect the material''s natural characteristics.  Powder-Coated Aluminum: Aluminum''s malleability makes it ideal for intricate, durable designs, offering a light, airy touch to robust constructions.  Laminate: The laminate used in our designs is partly made from melamine resin, one ' WHERE name='Base Table';
UPDATE products SET dimensions='Length: 250 cm; Height: 73 cm; Width: 110 cm', materials='Product Material                                              The tabletop is made of plywood with either laminate, linoleum, or oak veneer surface and a water-based lacquer. Plywood or ABS edges. Frame and legs in powder-coated aluminum.Oak Veneer: Slight color variations may reflect the material''s natural characteristics.Powder-Coated Aluminum: Aluminum''s malleability makes it ideal for intricate, durable designs, offering a light, airy touch to robust constructions.Laminate: The laminate used' WHERE name='Base Table With Castors';
UPDATE products SET dimensions='Height: 26,20 cm; Width: 18,70 cm; Depth: 8,70 cm; Diameter: 7,00 cm; Cord length: 100,00 cm', materials='The lamp is battery-powered, dimmable, and portable, delivering up to 10 hours of use at 100% intensity, 19 hours at 50%, and 48 hours at 20%. It is rated IP56.  The lamp body, and head are made from extruded and anodized aluminum for colored versions, and from extruded, polished, and anodized aluminum for polished versions. The diffuser is made from injection-molded opaque polycarbonate (PC), and the cord is made from extruded TPE. The lamp is produced without intentionally added PFAS.  Two bui' WHERE name='Beam Portable Lamp';
UPDATE products SET dimensions='Height: 26,20 cm; Width: 18,70 cm; Depth: 8,70 cm; Diameter: 8,20 cm; Cord length: 250,00 cm', materials='The surface is made from anodized aluminum or polished aluminum for a vibrant and distinct look and feel. It has a built-in energy-efficient LED light source, and the H45 cm has a user-replaceable LED light source. The lifetime of the light sources is defined as the time it takes until the light output/lumen maintenance reaches 80% (LM80) of the initial output. The user replaceable LED boards has a lifespan/lumen maintenance (LM90) of 56,000 hours.   Anodized Aluminum:  The aluminum is sandblast' WHERE name='Beam Table Lamp';
UPDATE products SET dimensions='Height: 15,40 cm; Width: 15,00 cm; Depth: 10,80 cm; Diameter: 7,00 cm; Cord length: 250,00 cm', materials='Extruded and anodized aluminum lamp body. Diffuser in opaque polycarbonate (PC).' WHERE name='Beam Wall Lamp';
UPDATE products SET dimensions='Height: 50,00 cm; Width: 50,00 cm; Depth: 7,25 cm; Diameter: 50,00 cm; Cord length: 250,00 cm', materials='Extruded aluminum profile, steel mounting plates. Injection molded ABS cover, soft diffusing textile shades (front and back)​. Integrated LED, that is temperature dimmable (dim to warmer lighting). Colored silicone band. Lumen Maintenance: 60.000h. Kelvin: 2200-3000K. CRI >90.' WHERE name='Calm Wall Lamp';
UPDATE products SET dimensions='Diameter: 50,00 cm', materials=NULL WHERE name='Calm Wall Lamp Silicone Band';
UPDATE products SET dimensions='Height: 9,00 cm; Width: 2,50 cm; Depth: 5,40 cm', materials=NULL WHERE name='Coil Coat Hook';
UPDATE products SET dimensions='Height: 9,50 cm; Width: 60,00 cm; Depth: 6,50 cm', materials='Anodized aluminum.' WHERE name='Coil Coat Rack';
UPDATE products SET dimensions='Height: 19,50 cm; Width: 15,00 cm; Depth: 20,00 cm', materials='Made from laser cut steel sheets, bent to form and coated with high quality powder. Brass, aluminium, or stainless steel with PVD vacuum treated surface.' WHERE name='Compile Bookend';
UPDATE products SET dimensions='Height: 67,50 cm; Length: 121,00 cm; Width: 42,00 cm', materials='Shelves are made from laser cut steel sheets, bent to form and coated with high quality powder coating. This coating gives the shelves a matt, abrasion-resistant and fingerprint-insensitive surface.' WHERE name='Compile Shelving System Configurations - Grey - Configuration 8';
UPDATE products SET dimensions='Height: 39,00 cm', materials='Shelves are made from laser cut steel sheets, bent to form and coated with high quality powder coating. This coating gives the shelves a matt, abrasion-resistant and fingerprint-insensitive surface.' WHERE name='Compile Shelving System Divider Pack';
UPDATE products SET dimensions='Height: 1,40 cm; Length: 120,00 cm; Width: 42,00 cm', materials='Shelves are made from laser cut steel sheets, bent to form and coated with high quality powder coating. This coating gives the shelves a matt, abrasion-resistant and fingerprint-insensitive surface.' WHERE name='Compile Shelving System Shelf';
UPDATE products SET dimensions='Height: 74,00 cm; Width: 118,50 cm; Depth: 98,00 cm; Seat height: 42,00 cm; Seat depth: 64,00 cm', materials='Seat and back frame are made from FSC™-certified (FSC-C028824) wood. The back frame is covered with cold foam filling and cotton wadding. The seat is made with zig-zag springs, felt, cold foam, and cotton wadding. Each module is upholstered in high-quality textiles or imitation leather and is kept together with connecting metal brackets.  Please note: The North American stock variants are not FSC™-certified.' WHERE name='Connect Modular Sofa';
UPDATE products SET dimensions='Height: 74,00 cm; Width: 235,00 cm; Depth: 98,00 cm; Seat height: 42,00 cm; Seat depth: 64,00 cm', materials='Seat and back frame are made in FSC™-certified (FSC-C028824) wood. The back frame is padded with cold foam and wadding, while the seat features zig-zag springs, felt, cold foam, and wadding. The modules are upholstered in high-quality textiles, imitation leather, or leather, with a thin layer of wadding underneath. Metal brackets are used to connect the modules.  Plastic: Plastic is a synthetic material made from various organic polymers, such as polyethylene or PVC.  Table: MDF with oak veneer ' WHERE name='Connect Modular Sofa 2-Seater';
UPDATE products SET dimensions='Height: 74,00 cm; Width: 418,00 cm; Depth: 98,00 cm; Seat height: 42,00 cm; Seat depth: 64,00 cm', materials='Seat and back frame are made in FSC™-certified (FSC-C028824) wood. The back frame is padded with cold foam and wadding, while the seat features zig-zag springs, felt, cold foam, and wadding. The modules are upholstered in high-quality textiles, imitation leather, or leather, with a thin layer of wadding underneath. Metal brackets are used to connect the modules.  Plastic: Plastic is a synthetic material made from various organic polymers, such as polyethylene or PVC.  Table: MDF with oak veneer ' WHERE name='Connect Modular Sofa 4-Seater - Configuration 1 - Remix 123';
UPDATE products SET dimensions='Height: 74,00 cm; Width: 237,00 cm; Depth: 196,00 cm; Seat height: 42,00 cm; Seat depth: 64,00 cm', materials='Seat and back frame are made in FSC™-certified (FSC-C028824) wood. The back frame is padded with cold foam and wadding, while the seat features zig-zag springs, felt, cold foam, and wadding. The modules are upholstered in high-quality textiles, imitation leather, or leather, with a thin layer of wadding underneath. Metal brackets are used to connect the modules.  Plastic: Plastic is a synthetic material made from various organic polymers, such as polyethylene or PVC.  Table: MDF with oak veneer ' WHERE name='Connect Modular Sofa Back-to-Back - Configuration 3 - Acca 731';
UPDATE products SET dimensions='Height: 69,00 cm; Width: 282,50 cm; Depth: 298,50 cm; Seat height: 40,00 cm; Seat depth: 66,00 cm', materials='Seat and back frame are made in FSC™-certified (FSC-C028824) wood. The back frame is padded with cold foam and wadding, while the seat features zig-zag springs, felt, cold foam, and wadding. The modules are upholstered in high-quality textiles, imitation leather, or leather, with a thin layer of wadding underneath. Metal brackets are used to connect the modules.  Plastic: Plastic is a synthetic material made from various organic polymers, such as polyethylene or PVC.  Table: MDF with oak veneer ' WHERE name='Connect Modular Sofa Corner - Configuration 1 - Remix 123';
UPDATE products SET dimensions='Height: 32,00 cm; Width: 46,00 cm; Depth: 92,00 cm; Seat height: 40,00 cm; Seat depth: 66,00 cm', materials='Table made using FSC™-certified (FSC-C028824) wood. MDF with oak veneer and a clear water-based lacquer finish. Legs made from solid oak with black water-based lacquer.' WHERE name='Connect Modular Sofa Table';
UPDATE products SET dimensions='Height: 69,00 cm; Seat height: 40,00 cm; Seat depth: 66,00 cm', materials='Seat and back frame are made in FSC™-certified (FSC-C028824) wood. The back frame is padded with cold foam and wadding, while the seat features zig-zag springs, felt, cold foam, and wadding. The modules are upholstered in high-quality textiles, imitation leather, or leather, with a thin layer of wadding underneath. Metal brackets are used to connect the modules.  Plastic: Plastic is a synthetic material made from various organic polymers, such as polyethylene or PVC.  Table: MDF with oak veneer ' WHERE name='Connect Soft Modular Sofa 4 Seater Configurations';
UPDATE products SET dimensions='Height: 69,00 cm; Seat height: 40,00 cm; Seat depth: 66,00 cm', materials='Seat and back frame are made in FSC™-certified (FSC-C028824) wood. The back frame is padded with cold foam and wadding, while the seat features zig-zag springs, felt, cold foam, and wadding. The modules are upholstered in high-quality textiles, imitation leather, or leather, with a thin layer of wadding underneath. Metal brackets are used to connect the modules.  Plastic: Plastic is a synthetic material made from various organic polymers, such as polyethylene or PVC.  Table: MDF with oak veneer ' WHERE name='Connect Soft Modular Sofa 4-Seater Configurations - Clay 12 - 4-Seater - Configuration 1';
UPDATE products SET dimensions='Height: 21,50 cm; Length: 21,00 cm; Depth: 14,00 cm; Cord length: 250,00 cm', materials='The lamp’s base is casted in aluminum, polished and finally powder coated. Cord in PVC.' WHERE name='Control Table Lamp';
UPDATE products SET dimensions='Height: 22,10 cm; Diameter: 9,90 cm', materials='The Corky Carafe is made in glass and is mouthblown and hand-polished. The Corky Carafe features a cork stopper in granulated cork. Dishwasher safe.' WHERE name='Corky Carafe';
UPDATE products SET dimensions='Height: 6,00 cm; Diameter: 8,50 cm', materials='The  Corky Glasses are made in glass and are mouthblown and hand-polished. Dishwasher safe.' WHERE name='Corky Glasses Set of 4';
UPDATE products SET dimensions='Height: 32,50 cm; Diameter: 23,00 cm; length: 260,00 cm', materials='Cosy in Grey Table Lamp is hand made, mouth blown in colored soda lime glass, cut grinded and polished by hand. PVC cord with a dimmer, plastic socket and an internal clear plastic construction to secure cord and socket. Bulb not included.' WHERE name='Cosy In Grey Table Lamp';
UPDATE products SET dimensions='Height: 40,00 cm; Length: 84,50 cm; Width: 40,00 cm; length: 84,40 cm', materials='Tabletop tiles made in ceramic stoneware treated with a stone sealer for extra stain protection. Tiles are placed loosely on top of the frame with rubber anti-slip pads securing the tiles in place. Frame in solid oak treated with either clear or dark oil, made using FSC™-certified (FSC-C028824) wood. Premounted felt glides. ​​' WHERE name='Couple Coffee Table 2 Plain 1 Wavy - Taupe/Dark Oiled Oak - 3 Tiles';
UPDATE products SET dimensions='Height: 75,80 cm; Width: 56,20 cm; Depth: 49,80 cm; Seat height: 46,00 cm; Seat depth: 36,80 cm', materials='The Cover Armchair is made from form-pressed wood. The wood is folded over the chair''s legs and backrest. This technically innovative wood layering helps lock the elements of the chair together. Upholstered seats with textile, imitation leather, or leather. Leather from selected premium leather suppliers. ​  Oak and Stained Dark Brown versions: The back, seat, and armrests in oak veneer, solid oak frame, and legs. Water-based lacquer. Plastic glides. ​  Colored versions: The back, seat, and armr' WHERE name='Cover Armchair';
UPDATE products SET dimensions='Height: 70,70 cm; Width: 66,30 cm; Depth: 61,20 cm; Seat height: 38,10 cm', materials='The Cover Lounge Chair is made from form-pressed wood. The wood is folded over the chair''s legs and backrest. This technically innovative wood layering helps lock the elements of the chair together. Upholstered seats with textile, imitation leather, or leather. Leather from selected premium leather suppliers. ​  Back and seat in oak veneer, solid oak frame and legs. Water-based lacquer. Plastic glides. ​  Oak veneer and Stained Dark Brown: slight color variations can occur due to the inherent ch' WHERE name='Cover Lounge Chair';
UPDATE products SET dimensions='Height: 75,40 cm; Width: 53,60 cm; Depth: 48,90 cm; Seat height: 45,40 cm', materials='The Cover Side Chair is made from form-pressed wood. The wood is folded over the chair''s legs and backrest. This technically innovative wood layering helps lock the elements of the chair together. Upholstered seats with textile, imitation leather, or leather. Leather from selected premium leather suppliers. ​  Back and seat in oak veneer, solid oak frame and legs. Water-based lacquer. Plastic glides. ​  Stacking Pad in felt made from 60% post-consumer recycled content.  Oak veneer and Stained Da' WHERE name='Cover Side Chair';
UPDATE products SET dimensions='Height: 112,00 cm; Width: 55,00 cm; Diameter: 19,00 cm; Cord length: 250,00 cm', materials='The lamp head, hinges, and base are made from die-cast aluminum. The lamp arms are made from extruded aluminum. All finished with a powder-coated surface. The diffuser is made from injection-molded plastic. The lamp is produced without intentionally added PFAS.' WHERE name='Dedicate Floor Lamp';
UPDATE products SET dimensions='Height: 36,80 cm; Length: 11,10 cm; Width: 19,00 cm; Depth: 19,00 cm; Diameter: 10,50 cm', materials='The lamp head and hinges are in die-casted aluminum, and the lamp arms are in extruded aluminum. All powder coated. Diffuser in injection molded plastic. Table base in machined steel. Clamp in die-casted aluminum and screw in stainless steel. Pin in machined steel screw and fixing nut.  Integrated dimmable LED light source. Lumen: 750lm on 100% brightness. Lumen Maintenance (80%): >43.000h. Kelvin: 3000K. CRI >90. The lamp comes with a built-in 8-hour timer.' WHERE name='Dedicate Table Lamp';
UPDATE products SET dimensions='Height: 36,80 cm; Length: 11,10 cm; Width: 19,00 cm; Depth: 19,00 cm; Diameter: 10,50 cm', materials='Lamp head and hinges in die-casted aluminum, lamp arms in extruded aluminum. All powder coated. Diffuser in injection molded plastic. Wall Mount in die-casted aluminum.  Integrated dimmable LED light source. Lumen: 750lm on 100% brightness. Lumen Maintenance (80%): >43.000h. Kelvin: 3000K. CRI >90. The lamp comes with a built-in 8-hour timer.' WHERE name='Dedicate Wall Lamp';
UPDATE products SET dimensions='Depth: 44,00 cm; Diameter: 13,00 cm', materials='The Dots Ceramic is made from earthenware with glaze. The Dots Ceramic is made in an organic material. The surface is made with a reactive glaze, giving each single Dots Ceramic a unique expression. Slight color variations may appear as a natural characteristic of the design''s materiality.' WHERE name='Dots Ceramic';
UPDATE products SET dimensions='Diameter: 2,70 cm', materials='The Dots Metal is made from anodized solid aluminum. Produced on a CNC lathering machine, carefully lacquered and packed.' WHERE name='Dots Metal';
UPDATE products SET dimensions='Diameter: 6,50 cm', materials='The Dots Wood is made from first class oiled oak or walnut. Colored versions is made from painted ash wood. The wood is cut, glued together in two pieces and processed in a CNC turning lathe. Polished and oiled. This product is made in an organic material. Natural variations in the surface and color can occur as a result of this, giving each single product a unique expression.' WHERE name='Dots Wood';
UPDATE products SET dimensions='Height: 106,00 cm; Width: 95,50 cm; Depth: 100,00 cm; Seat height: 40,00 cm; Seat depth: 52,50 cm', materials='The Doze Lounge Chair & Ottoman are made from metal, foam, and wadding and finished with textile, imitation leather, or leather upholstery. The leather comes from selected premium leather suppliers.   The Doze Lounge Chair & Ottoman are upholstered in molded foam with an embedded steel frame. Please note that the Doze Lounge Chair & Ottoman''s upholstery cannot be removed. Swivel base in polished or powder-coated casted aluminum. Plastic glides in black.' WHERE name='Doze Lounge Chair High Back Swivel Base';
UPDATE products SET dimensions='Height: 106,00 cm; Width: 95,50 cm; Depth: 100,00 cm; Seat height: 40,00 cm; Seat depth: 52,50 cm', materials='The Doze Lounge Chair & Ottoman are made from metal, foam, and wadding and finished with textile, imitation leather, or leather upholstery. The leather comes from selected premium leather suppliers.   The Doze Lounge Chair & Ottoman are upholstered in molded foam with an embedded steel frame. Please note that the Doze Lounge Chair & Ottoman''s upholstery cannot be removed. Tube base in chromed or powder-coated steel. Plastic glides in black.' WHERE name='Doze Lounge Chair High Back Tube Base';
UPDATE products SET dimensions='Height: 78,00 cm; Width: 95,50 cm; Depth: 86,00 cm; Seat height: 40,00 cm; Seat depth: 52,50 cm', materials='The Doze Lounge Chair & Ottoman are made from metal, foam, and wadding and finished with textile, imitation leather, or leather upholstery. The leather comes from selected premium leather suppliers.   The Doze Lounge Chair & Ottoman are upholstered in molded foam with an embedded steel frame. Please note that the Doze Lounge Chair & Ottoman''s upholstery cannot be removed. Swivel base in polished or powder-coated casted aluminum. Plastic glides in black.' WHERE name='Doze Lounge Chair Low Back Swivel Base';
UPDATE products SET dimensions='Height: 78,00 cm; Width: 95,50 cm; Depth: 86,00 cm; Seat height: 40,00 cm; Seat depth: 52,50 cm', materials='The Doze Lounge Chair & Ottoman are made from metal, foam, and wadding and finished with textile, imitation leather, or leather upholstery. The leather comes from selected premium leather suppliers.   The Doze Lounge Chair & Ottoman are upholstered in molded foam with an embedded steel frame. Please note that the Doze Lounge Chair & Ottoman''s upholstery cannot be removed. Tube base in chromed or powder-coated steel. Plastic glides in black.' WHERE name='Doze Lounge Chair Low Back Tube Base';
UPDATE products SET dimensions='Height: 40,00 cm; Width: 64,00 cm; Depth: 52,00 cm; Seat height: 40,00 cm', materials='The Doze Lounge Chair & Ottoman are made from metal, foam, and wadding and finished with textile, imitation leather, or leather upholstery. The leather comes from selected premium leather suppliers.   The Doze Lounge Chair & Ottoman are upholstered in molded foam with an embedded steel frame. Please note that the Doze Lounge Chair & Ottoman''s upholstery cannot be removed. Swivel base in polished or powder-coated casted aluminum. Plastic glides in black.' WHERE name='Doze Ottoman Swivel Base';
UPDATE products SET dimensions='Height: 40,00 cm; Width: 64,00 cm; Depth: 52,00 cm; Seat height: 40,00 cm', materials='The Doze Lounge Chair & Ottoman are made from metal, foam, and wadding and finished with textile, imitation leather, or leather upholstery. The leather comes from selected premium leather suppliers.   The Doze Lounge Chair & Ottoman are upholstered in molded foam with an embedded steel frame. Please note that the Doze Lounge Chair & Ottoman''s upholstery cannot be removed. Tube base in chromed or powder-coated steel. Plastic glides in black.' WHERE name='Doze Ottoman Tube Base';
UPDATE products SET dimensions='Height: 80,00 cm; Width: 100,00 cm; Depth: 110,00 cm; Seat height: 32,30 cm; Seat depth: 100,00 cm', materials='Rolled brushed stainless steel sheet with welded stainless steel sides.' WHERE name='Dream View Bench';
UPDATE products SET dimensions='Height: 23,00 cm; Length: 12,50 cm; Width: 12,50 cm; Diameter: 12,50 cm; Cord length: 400,00 cm', materials='The E27 Pendant Lamp is pressed in vulcanised silicone rubber under high temperature. Inside plastic socket and PVC cord is assembled by hand.' WHERE name='E27 Pendant Lamp';
UPDATE products SET dimensions='Height: 73,00 cm; Length: 205,00 cm; Width: 100,00 cm', materials='The table top and base are made from FSC™-certified (FSC-C028824) solid oak, treated with either a clear or a dark oil. Felt glides.  Extension leaves can easily be inserted into each end of the table frame to extend the length of the table. Extension leaves are not included, and can be purchased separately.' WHERE name='Earnest Extendable Table';
UPDATE products SET dimensions='Length: 44,00 cm; Width: 100,00 cm', materials='The extension leaves for the Earnest Extendable Table, which can be inserted into its ends, are made from FSC™-certified (FSC-C028824) solid oak and are treated with either a clear or dark oil.' WHERE name='Earnest Extendable Table Extension Leaves';
UPDATE products SET dimensions='Height: 21,50 cm; Width: 13,16 cm; Depth: 13,16 cm; Diameter: 13,16 cm; Cord length: 90,00 cm', materials='Battery-powered, dimmable and portable lamp with 8 hours of battery life on 100% intensity, 16 hours on 50% intensity and 29 hours on 25% intensity. Body and lampshade made in injection-molded ABS plastic, with an integrated LED light source. Diffuser in opal acrylic. Charging dock made in injection-molded ABS plastic with USB-C cable.​​  Lumen Maintenance (L70): 52.000h. Lumen: 230lm on 100% brightness. Kelvin: 2700K. CRI >90. ​​' WHERE name='Ease Portable Lamp';
UPDATE products SET dimensions='Height: 39,00 cm; Width: 52,00 cm; Depth: 38,00 cm; Seat height: 36,00 cm', materials='The Echo Pouf frame is made from FSC™-certified (FSC-C028824) wood, high-Resilience foam, and textile or imitation leather upholstery.  Please note: The North American stock variants are not FSC™-certified.' WHERE name='Echo Pouf';
UPDATE products SET dimensions='Height: 77,00 cm; Width: 54,50 cm; Depth: 56,00 cm; Seat height: 46,00 cm; Seat depth: 46,00 cm', materials='Shell - Without Upholstery: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% FSC™- certified (FSC-C028824) wood fibers. The recycled plastic comes from post-industrial waste. Due to the shell’s partly natural material, slight color variations can occur.  Shell – Upholstered Variants: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% wood fibers. The recycled plasti' WHERE name='Fiber Armchair Sled Base';
UPDATE products SET dimensions='Height: 77,00 cm; Width: 54,50 cm; Depth: 56,00 cm; Seat height: 46,00 cm; Seat depth: 46,00 cm', materials='Shell - Without Upholstery: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% FSC™- certified (FSC-C028824) wood fibers. The recycled plastic comes from post-industrial waste. Due to the partly natural material of the shell, slight color variations can occur.  Shell – Upholstered Variants: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% wood fibers. The recycled p' WHERE name='Fiber Armchair Swivel Base';
UPDATE products SET dimensions='Height: 77,00 cm; Width: 54,50 cm; Depth: 56,00 cm; Seat height: 46,00 cm; Seat depth: 46,00 cm', materials='Shell - Without Upholstery: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% FSC™- certified (FSC-C028824) wood fibers. The recycled plastic comes from post-industrial waste. Due to the shell’s partly natural material, slight color variations can occur.  Shell – Upholstered Variants: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% wood fibers. The recycled plasti' WHERE name='Fiber Armchair Tube Base';
UPDATE products SET dimensions='Height: 77,00 cm; Width: 54,50 cm; Depth: 56,00 cm; Seat height: 46,00 cm; Seat depth: 46,00 cm', materials='Shell - Without Upholstery: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% FSC™- certified (FSC-C028824) wood fibers. The recycled plastic comes from post-industrial waste. Due to the shell’s partly natural material, slight color variations can occur.  Shell – Upholstered Variants: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% wood fibers. The recycled plasti' WHERE name='Fiber Armchair Wood Base';
UPDATE products SET dimensions='Height: 77,50 cm; Width: 63,50 cm; Depth: 60,50 cm; Seat height: 49,00 cm; Seat depth: 49,30 cm', materials='The shell is made using 100% recycled plastic mixed with strength-improving additives. The recycled plastic comes from post-consumer waste.  Fully upholstered in textile, imitation leather or leather.​  Base: Swivel base in powder coated aluminum made using minimum 95% recycled die casted aluminum. The recycled die casted aluminum comes from a mix between post-industrial and post-consumer waste. Cylinder in steel. Plastic glides.' WHERE name='Fiber Conference Armchair Swivel Base';
UPDATE products SET dimensions='Height: 77,50 cm; Width: 63,50 cm; Depth: 60,50 cm; Seat height: 49,00 cm; Seat depth: 49,30 cm', materials='The shell is made using 100% recycled plastic mixed with strength-improving additives. The recycled plastic comes from post-consumer waste.  Fully upholstered in textile, imitation leather or leather.​  Base: Tube base in powder coated steel.' WHERE name='Fiber Conference Armchair Tube Base';
UPDATE products SET dimensions='Height: 77,50 cm; Width: 63,50 cm; Depth: 60,50 cm; Seat height: 49,00 cm; Seat depth: 49,30 cm', materials='The shell is made using 100% recycled plastic mixed with strength-improving additives. The recycled plastic comes from post-consumer waste.  Fully upholstered in textile, imitation leather or leather.​  Base: Wood base in FSC™-certified (FSC-C028824) oak with water-based lacquer. For Stained Dark Brown version only: Please note that slight color variations can occur due to the inherent characteristics of the material. Plastic glides.' WHERE name='Fiber Conference Armchair Wood Base';
UPDATE products SET dimensions='Height: 88,10 cm; Width: 75,00 cm; Depth: 83,30 cm; Seat height: 42,80 cm; Seat depth: 58,00 cm', materials='The shell is made using 100% recycled plastic mixed with strength-improving additives. The recycled plastic comes from post-consumer waste. Fully upholstered in textile, imitation leather, or leather.​  Base: 4-star swivel base in powder-coated aluminum is made using a minimum of 95% recycled cast aluminum. The recycled cast aluminum comes from a mix of post-industrial and post-consumer waste. Aluminum''s malleability makes it a grand fit for highly detailed, durable Muutoproducts, bringing a lig' WHERE name='Fiber Lounge Armchair Swivel Base';
UPDATE products SET dimensions='Height: 88,10 cm; Width: 75,00 cm; Depth: 83,30 cm; Seat height: 42,80 cm; Seat depth: 58,00 cm', materials='Shell - Without Upholstery: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% FSC™- certified (FSC-C028824) wood fibers. The recycled plastic comes from post-industrial waste. Due to the shell’s partly natural material, slight color variations can occur.  Shell – Upholstered Variants: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% wood fibers. The recycled plasti' WHERE name='Fiber Lounge Armchair Tube Base';
UPDATE products SET dimensions='Height: 88,10 cm; Width: 75,00 cm; Depth: 83,30 cm; Seat height: 42,80 cm; Seat depth: 58,00 cm', materials='Shell - Without Upholstery: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% FSC™- certified (FSC-C028824) wood fibers. The recycled plastic comes from post-industrial waste. Due to the shell’s partly natural material, slight color variations can occur.  Shell – Upholstered Variants: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% wood fibers. The recycled plasti' WHERE name='Fiber Lounge Armchair Wood Base';
UPDATE products SET dimensions='Height: 74,40 cm; Width: 60,00 cm; Depth: 69,00 cm; Seat height: 38,00 cm; Seat depth: 49,00 cm', materials='Shell - Without Upholstery: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% FSC™- certified (FSC-C028824) wood fibers. The recycled plastic comes from post-industrial waste. Due to the shell’s partly natural material, slight color variations can occur.  Shell – Upholstered Variants: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% wood fibers. The recycled plasti' WHERE name='Fiber Lounge Chair Tube Base';
UPDATE products SET dimensions='Height: 74,40 cm; Width: 60,00 cm; Depth: 69,00 cm; Seat height: 38,00 cm; Seat depth: 49,00 cm', materials='Shell - Without Upholstery: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% FSC™- certified (FSC-C028824) wood fibers. The recycled plastic comes from post-industrial waste. Due to the shell’s partly natural material, slight color variations can occur.  Shell – Upholstered Variants: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% wood fibers. The recycled plasti' WHERE name='Fiber Lounge Chair Wood Base';
UPDATE products SET dimensions='Height: 77,00 cm; Width: 54,50 cm; Depth: 56,00 cm; Seat height: 46,00 cm; Seat depth: 46,00 cm', materials='Made using 100% recycled plastic mixed with UV stabilizers that keep color-fading at a minimum, protecting it from the impact of the sun. The recycled plastic comes from post-industrial waste.  Tube base in galvanized steel with a weather-resistant deep matte powder coating.  Plastic glides for outdoor use.' WHERE name='Fiber Outdoor Armchair';
UPDATE products SET dimensions='Height: 77,00 cm; Width: 49,50 cm; Depth: 53,00 cm; Seat height: 46,00 cm; Seat depth: 45,00 cm', materials='Made using 100% recycled plastic mixed with UV stabilizers that keep color-fading at a minimum, protecting it from the impact of the sun. The recycled plastic comes from post-industrial waste.  Tube base in galvanized steel with a weather-resistant deep matte powder coating.  Plastic glides for outdoor use.' WHERE name='Fiber Outdoor Side Chair';
UPDATE products SET dimensions='Height: 77,00 cm; Width: 55,50 cm; Depth: 53,00 cm; Seat height: 46,00 cm; Seat depth: 45,00 cm', materials='Shell - Without Upholstery: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% FSC™- certified (FSC-C028824) wood fibers. The recycled plastic comes from post-industrial waste. Due to the shell’s partly natural material, slight color variations can occur.  Shell – Upholstered Variants: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% wood fibers. The recycled plasti' WHERE name='Fiber Side Chair A-Base';
UPDATE products SET dimensions='Height: 77,00 cm; Width: 47,50 cm; Depth: 51,50 cm; Seat height: 46,00 cm; Seat depth: 45,00 cm', materials='Shell - Without Upholstery: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% FSC™- certified (FSC-C028824) wood fibers. The recycled plastic comes from post-industrial waste. Due to the shell’s partly natural material, slight color variations can occur.  Shell – Upholstered Variants: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% wood fibers. The recycled plasti' WHERE name='Fiber Side Chair Sled Base';
UPDATE products SET dimensions='Height: 77,00 cm; Width: 47,50 cm; Depth: 53,00 cm; Seat height: 46,00 cm; Seat depth: 45,00 cm', materials='Shell - Without Upholstery: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% FSC™- certified (FSC-C028824) wood fibers. The recycled plastic comes from post-industrial waste. Due to the partly natural material of the shell, slight color variations can occur.  Shell – Upholstered Variants: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% wood fibers. The recycled p' WHERE name='Fiber Side Chair Swivel Base';
UPDATE products SET dimensions='Height: 77,00 cm; Width: 51,00 cm; Depth: 53,00 cm; Seat height: 46,00 cm; Seat depth: 45,00 cm', materials='Shell - Without Upholstery: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% FSC™- certified (FSC-C028824) wood fibers. The recycled plastic comes from post-industrial waste. Due to the shell’s partly natural material, slight color variations can occur.  Shell – Upholstered Variants: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% wood fibers. The recycled plasti' WHERE name='Fiber Side Chair Tube Base';
UPDATE products SET dimensions='Height: 77,00 cm; Width: 49,50 cm; Depth: 53,00 cm; Seat height: 46,00 cm; Seat depth: 45,00 cm', materials='Shell - Without Upholstery: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% FSC™- certified (FSC-C028824) wood fibers. The recycled plastic comes from post-industrial waste. Due to the shell’s partly natural material, slight color variations can occur.  Shell – Upholstered Variants: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% wood fibers. The recycled plasti' WHERE name='Fiber Side Chair Wood Base';
UPDATE products SET dimensions='Height: 77,50 cm; Width: 63,50 cm; Depth: 60,50 cm; Seat height: 49,00 cm; Seat depth: 49,30 cm', materials='Shell from 100% recycled plastic mixed with strength-improving additives. The recycled plastic comes from post-consumer waste.  Seat, back and armrest is clad with multiple layers of foam and wadding and finished with textile, imitation leather or leather upholstery. Leather from selected premium leather suppliers. ​  Swivel base in powder coated aluminum. Plastic glides.' WHERE name='Fiber Soft Armchair Swivel Base';
UPDATE products SET dimensions='Height: 77,50 cm; Width: 63,50 cm; Depth: 60,50 cm; Seat height: 49,00 cm; Seat depth: 49,30 cm', materials='Shell from 100% recycled plastic mixed with strength-improving additives. The recycled plastic comes from post-consumer waste.  Seat, back and armrest is clad with multiple layers of foam and wadding and finished with textile, imitation leather or leather upholstery. Leather from selected premium leather suppliers. ​  Tube base in powder coated steel. Plastic glides.​' WHERE name='Fiber Soft Armchair Tube Base';
UPDATE products SET dimensions='Height: 77,50 cm; Width: 63,50 cm; Depth: 60,50 cm; Seat height: 49,00 cm; Seat depth: 49,30 cm', materials='Shell from 100% recycled plastic mixed with strength-improving additives. The recycled plastic comes from post-consumer waste.  Seat, back and armrest is clad with multiple layers of foam and wadding and finished with textile, imitation leather or leather upholstery. Leather from selected premium leather suppliers. ​  Wood base in FSC™-certified (FSC-C028824) oak with water-based lacquer. For Stained Dark Brown version only: Please note that slight color variations can occur due to the inherent ' WHERE name='Fiber Soft Armchair Wood Base';
UPDATE products SET dimensions='Height: 46,00 cm; Width: 45,00 cm; Depth: 38,80 cm; Seat height: 45,00 cm; Seat depth: 32,00 cm', materials='Shell - Without Upholstery: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% FSC™- certified (FSC-C028824) wood fibers. The recycled plastic comes from post-industrial waste. Due to the shell’s partly natural material, slight color variations can occur.  Shell – Upholstered Variants: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% wood fibers. The recycled plasti' WHERE name='Fiber Stool Tube Base';
UPDATE products SET dimensions='Height: 46,00 cm; Width: 45,00 cm; Depth: 35,50 cm; Seat height: 45,00 cm; Seat depth: 32,00 cm', materials='Shell - Without Upholstery: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% FSC™- certified (FSC-C028824) wood fibers. The recycled plastic comes from post-industrial waste. Due to the shell’s partly natural material, slight color variations can occur.  Shell – Upholstered Variants: The shell is made using 100% recycled plastic reinforced with strength-improving additives and mixed with up to 25% wood fibers. The recycled plasti' WHERE name='Fiber Stool Wood Base';
UPDATE products SET dimensions='Height: 1,80 cm; Width: 60,00 cm; Depth: 2,40 cm; Cord length: 400,00 cm', materials='Body in pressure-die casted and extruded, powder coated aluminum. Diffuser in extruded opaque plastic. Lamp driver integrated in white plastic canopy.​  Dimmable, integrated and replaceable LED light designed for Right to Repair, meaning that light source can be replaced by an electrician only. Lumen maintenance: 35.000h. Kelvin: 2700K. CRI: >90. ​' WHERE name='Fine Suspension Lamp Grey - 60 CM';
UPDATE products SET dimensions='Height: 1,80 cm; Width: 60,00 cm; Depth: 2,40 cm; Cord length: 200,00 cm', materials='Body in pressure-die casted and extruded, powder-coated aluminum. Diffuser in extruded opaque plastic. Single profiles come with an inline dimmer and plug. Configurations come with a wall/ceiling mounted driver integrated in white plastic driver box. Configurations are dimmable when hardwired—no dimmer on cable.  Dimmable, integrated, and non-user replaceable LED light designed for Right to Repair means that only an electrician can replace the light source. Lumen maintenance: 30.000h. Kelvin: 27' WHERE name='Fine Wall/Ceiling Lamp Black - Configuration 5';
UPDATE products SET dimensions='Height: 2,60 cm; Width: 15,00 cm; Depth: 11,40 cm', materials='High pressure casting in aluminum and powder coated with heat resistant PU lacquer. Small silicone feet are attached underneath the candlestick to protect table tops or other surfaces from excessive heat, should the candle burn down and heat up the aluminum element.' WHERE name='Float Candlestick';
UPDATE products SET dimensions='Height: 40,06 cm; Length: 95,00 cm; Width: 95,50 cm', materials='Trays and legs in powder-coated steel. Wheels in powder-coated steel and rubber.  Powder-coated steel: Steel is an alloy of iron and carbon. Powder-coated steel has a subtle, textured expression and elegant feel while adding durability to the design and making it more resistant to corrosion.' WHERE name='Flow Coffee Table';
UPDATE products SET dimensions='Height: 14,30 cm; Diameter: 23,00 cm; Cord length: 350,00 cm', materials='The lampshade is made from mouth blown, white silk mat opal glass. The edge on top of the lamp is grinded and polished. The lidt is made in Nylon66 with fibre glass.' WHERE name='Fluid Pendant Lamp';
UPDATE products SET dimensions='Height: 29,00 cm; Diameter: 16,00 cm; Cord length: 210,00 cm', materials='The Focus Table Lamp’s wooden components are shaped on a lathe machine. The electrical parts are hidden inside the lamps components, which are glued together to hide that they were ever apart. Thereafter, the lamp is painted. Ash wood and PVC cord.' WHERE name='Focus Table Lamp';
UPDATE products SET dimensions='Height: 40,00 cm; Width: 40,00 cm; Depth: 4,00 cm', materials='Powder coated steel. Mirror glass sheet. A steel plate is worked through three rounds to shape the mirror’s frame. The surface is powder coated. Lastly, the mirror glass is gently installed to create the little gap between the mirror’s frame and mirror glass.' WHERE name='Framed Mirror';
UPDATE products SET dimensions='Height: 30,00 cm; Width: 25,00 cm; Depth: 6,50 cm', materials='Mirror-finish stainless steel' WHERE name='Gaze Mirror';
UPDATE products SET dimensions='Height: 18,50 cm; Width: 21,00 cm; Depth: 21,00 cm; Diameter: 21,00 cm; Cord length: 400,00 cm', materials='Lamp Shade is made in mixture of bamboo fibers and polypropolene. PVC cord. The lamp’s shade is made under high pressure casting. Shade and electrical componenets are hereafter assembled by hand.' WHERE name='Grain Pendant Lamp';
UPDATE products SET dimensions='Height: 2,00 cm; Diameter: 16,00 cm', materials='Raw marble is cut, shaped and the surface is oiled.' WHERE name='Groove Trivet';
UPDATE products SET dimensions='Height: 36,50 cm; Diameter: 85,00 cm', materials='The coffee table is crafted from high-quality, cement-based terrazzo and treated with a water and oil repellent stone sealer. Terrazzo consists of natural stone chips set in a resilient cement matrix, resulting in subtle variations in pattern, color, and texture that make each table unique. The table’s smooth, solid finish is suitable for both indoor and outdoor use. When placed outdoors, the material will naturally weather and develop a distinctive patina over time. The table is fitted with pla' WHERE name='Halves Coffee Table';
UPDATE products SET dimensions='Height: 70,00 cm; Width: 198,00 cm; Depth: 107,00 cm; Seat height: 38,00 cm; Seat depth: 74,00 cm', materials='Frame in powder-coated steel. Modules in an FSC™-certified (FSC-C028824) wood construction with foam and wadding. Fully upholstered with textile, imitation leather, or leather. Leather from selected premium leather suppliers.​​  Cushions made from a foam core with wadding, finished with upholstery in either textile, leather or imitation leather.' WHERE name='In Situ Modular Sofa 2-Seater Configurations - Frame and Module - Ocean 80/Black - 2-Seater - Configuration 7';
UPDATE products SET dimensions='Height: 70,00 cm; Width: 279,00 cm; Depth: 107,00 cm; Seat height: 38,00 cm; Seat depth: 74,00 cm', materials='Frame in powder-coated steel. Modules in an FSC™-certified (FSC-C028824) wood construction with foam and wadding. Fully upholstered with textile, imitation leather, or leather. Leather from selected premium leather suppliers.​​  Cushions made from a foam core with wadding, finished with upholstery in either textile, leather or imitation leather.' WHERE name='In Situ Modular Sofa 3-Seater Configurations - Frame and Module - Clay 12/Black - 3-Seater - Configuration 9';
UPDATE products SET dimensions='Height: 70,00 cm; Width: 360,00 cm; Depth: 107,00 cm; Seat height: 38,00 cm; Seat depth: 74,00 cm', materials='Frame in powder-coated steel. Modules in an FSC™-certified (FSC-C028824) wood construction with foam and wadding. Fully upholstered with textile, imitation leather, or leather. Leather from selected premium leather suppliers.​​  Cushions made from a foam core with wadding, finished with upholstery in either textile, leather or imitation leather.' WHERE name='In Situ Modular Sofa 4-Seater Configurations - Frame and Module - Clay 15/Black - 4-Seater - Configuration 5';
UPDATE products SET dimensions='Height: 70,00 cm; Width: 278,00 cm; Depth: 278,00 cm; Seat height: 38,00 cm; Seat depth: 74,00 cm', materials='Frame in powder-coated steel. Modules in an FSC™-certified (FSC-C028824) wood construction with foam and wadding. Fully upholstered with textile, imitation leather, or leather. Leather from selected premium leather suppliers.​​  Cushions made from a foam core with wadding, finished with upholstery in either textile, leather or imitation leather.' WHERE name='In Situ Modular Sofa Corner Configurations - Frame and Module - Ocean 80/Black - Corner - Configuration 9';
UPDATE products SET dimensions='Height: 30,00 cm; Width: 70,00 cm', materials='Cushions made from a foam core with wadding, finished with upholstery in either textile, leather or imitation leather.' WHERE name='In Situ Modular Sofa Cushion';
UPDATE products SET dimensions='Height: 70,00 cm; Width: 99,00 cm; Depth: 107,00 cm; Seat height: 38,00 cm; Seat depth: 74,00 cm', materials='Frame in powder-coated steel. Modules in an FSC™-certified (FSC-C028824) wood construction with foam and wadding. Fully upholstered with textile, imitation leather, or leather. Leather from selected premium leather suppliers.​​  Cushions made from a foam core with wadding, finished with upholstery in either textile, leather or imitation leather.' WHERE name='In Situ Modular Sofa Modules';
UPDATE products SET dimensions='Height: 26,30 cm; Width: 27,40 cm; Depth: 12,90 cm', materials='Pigmented porcelain; Unglazed on the outside, glazed on the inside. Small variations in the surface and color of the object are a natural and unique trait of the material.  Earthenware: Liquid earthenware clay is poured into a plaster mold from which the design is molded. The Kink Vase is then polished with a wet sponge and fired at 1000°. After firing, the design is glazed with glossy glaze on the inside and a matt glaze on the outside, the design is then taken to the kiln again, this time at 1' WHERE name='Kink Vase';
UPDATE products SET dimensions='Height: 41,50 cm; Length: 15,50 cm; Width: 18,00 cm; Cord length: 180,00 cm', materials='Aluminum, Brass, Coloured PVC cord. The Leaf Table Lamp is a result of a process combining turned and casted aluminum and steel, with a strong powder coating as paint.  It has a build-in energy-efficient LED bulb with a Lumen Maintenance (Lifetime) of L90 B10 35.000 hours.' WHERE name='Leaf Table Lamp';
UPDATE products SET dimensions='Height: 36,50 cm; Length: 23,20 cm; Width: 10,70 cm; Depth: 10,70 cm; Cord length: 150,00 cm', materials='Lamphead is made in pressure-die casted, powder coated aluminum. Stem in powder coated steel. Polycarbonate diffuser and PVC cord with GST1813 plug.' WHERE name='Linear Mounted Lamp Black - 209,2 cm';
UPDATE products SET dimensions='Height: 5,40 cm; Length: 87,20 cm; Width: 10,70 cm; Depth: 10,70 cm; Cord length: 400,00 cm', materials='Lamphead in pressure-die casted and extruded, powder coated aluminum. Stem in powder coated steel. Diffuser in polycarbonate. PVC cord.' WHERE name='Linear Pendant Lamp Black - 169,2 cm';
UPDATE products SET dimensions='Height: 45,50 cm; Length: 110,00 cm; Width: 110,00 cm; Depth: 39,00 cm; Seat height: 45,50 cm; Seat depth: 39,00 cm', materials='Powder-Coated Steel: The frame and seat are made from galvanized steel and have a weather-resistant, deep matt, UV-resistant powder-coated finish, making them suitable for outdoor use. The legs have plastic glides. Powder-coated steel has a subtle, textured expression and elegant feel while adding durability to the design.  Warm Galvanized Steel: The frame and seat are made from warm galvanized steel, which undergoes untreated steel being dipped in a liquid zinc bath, making them suitable for ou' WHERE name='Linear Steel Bench Warm Galvanized Steel - 170 x 34 cm';
UPDATE products SET dimensions='Height: 78,70 cm; Width: 68,40 cm; Depth: 70,50 cm; Seat height: 38,80 cm; Seat depth: 50,90 cm', materials='Powder-Coated Steel: The frame and seat are made from galvanized steel and have a weather-resistant, deep matt, UV-resistant powder-coated finish, making them suitable for outdoor use. The legs have plastic glides. Powder-coated steel has a subtle, textured expression and elegant feel while adding durability to the design.  Powder-Coated Steel: Steel is an alloy of iron with carbon. Powder-coated steel has a subtle, textured expression and elegant feel while adding durability to the design and m' WHERE name='Linear Steel Lounge Armchair';
UPDATE products SET dimensions='Height: 73,50 cm; Length: 140,00 cm; Width: 80,00 cm; Seat height: 66,30 cm', materials='Powder-Coated Steel: The frame and seat are made from galvanized steel and have a weather-resistant, deep matt, UV-resistant powder-coated finish, making them suitable for outdoor use. The legs have plastic glides. Powder-coated steel has a subtle, textured expression and elegant feel while adding durability to the design.  Warm Galvanized Steel: The frame and seat are made from warm galvanized steel, which undergoes untreated steel being dipped in a liquid zinc bath, making them suitable for ou' WHERE name='Linear Steel Table Grey - 220 x 90 cm';
UPDATE products SET dimensions='Height: 74,00 cm; Length: 240,00 cm; Width: 110,00 cm', materials='Tabletop in Oak Veneer, Black version in Ash Veneer, Black Nanolaminate or White Laminate.  Black Nanolaminate and White Laminate has an ABS edge. It is not possible to mix multiple tabletop finishes in a Linear System configuration.  Table frame in veneered plywood and legs in Solid Oak. Felt glides included.  Oak Veneer color variations: The Oak Veneer tabletops of the Linear System Series are made using high-quality mix-matched veneer to reduce differences in the visual appearance from tablet' WHERE name='Linear System Middle Module';
UPDATE products SET dimensions='Height: 35,00 cm; Length: 75,00 cm; Width: 15,00 cm', materials='Screens are in solid oak and veneered MDF with powder coated aluminum fixing knobs. Possibility of upholstery on Screens.' WHERE name='Linear System Screen Oak - 178 cm';
UPDATE products SET dimensions='Height: 15,00 cm; Length: 24,00 cm; Width: 24,00 cm; Diameter: 24,00 cm', materials='Tray 170 cm and 75 cm in solid oak and oak veneer. Tray Ø24 and Ø36 in solid oak. All with powder coated aluminum fixing knobs.  Linear System Tray 75 cm is made from FSC™-certified (FSC-C028824) wood.' WHERE name='Linear System Tray Black - 75 cm';
UPDATE products SET dimensions='Height: 36,50 cm; Length: 23,20 cm; Width: 16,50 cm; Depth: 16,50 cm; Cord length: 250,00 cm', materials='Lamphead in pressure-die casted, powder coated aluminum. Stem in powder coated steel. Polycarbonate diffuser and PVC cord.' WHERE name='Linear Table Lamp Black';
UPDATE products SET dimensions='Height: 46,00 cm; Width: 110,00 cm; Depth: 39,40 cm; Seat height: 46,00 cm; Seat depth: 39,40 cm', materials='The seat is made in oak veneer with veneered plywood aprons and solid oak legs all made using FSC™-certified (FSC-C028824) wood.   Oak veneer: slight color variations can occur due to the inherent characteristics of the material.  Lacquered Oak: Oak is a traditionally Scandinavian material with durable abilities against factors such as water and fungi alongside a high level of strength, giving it long-lasting properties fit for furniture.  Lacquered Oak Veneer: Oak is a traditionally Scandinavia' WHERE name='Linear Wood Bench';
UPDATE products SET dimensions='Height: 74,00 cm; Length: 140,00 cm; Width: 90,30 cm; Seat height: 65,50 cm', materials='Tabletop is oak veneer with veneered plywood aprons and solid oak legs all made using FSC™-certified (FSC-C028824) wood.  Oak veneer: slight color variations can occur due to the inherent characteristics of the material.  Lacquered Oak: Oak is a traditionally Scandinavian material with durable abilities against factors such as water and fungi alongside a high level of strength, giving it long-lasting properties fit for furniture.  Lacquered Oak Veneer: Oak is a traditionally Scandinavian materia' WHERE name='Linear Wood Table';
UPDATE products SET dimensions='Height: 78,70 cm; Width: 42,40 cm; Depth: 48,80 cm; Seat height: 46,00 cm; Seat depth: 40,90 cm', materials='The seat and back are constructed with beech veneer layers and outer oak surface veneers with water-based lacquer. Upholstered seats with textile, imitation leather, or leather. Leather from selected premium leather suppliers. ​Frame in powder-coated steel. Plastic glides.​  Oak veneer and Stained Dark Brown: slight color variations can occur due to the material''s inherent characteristics.' WHERE name='Loft Chair';
UPDATE products SET dimensions='Depth: 6,00 cm; Diameter: 35,00 cm; Cord length: 300,00 cm', materials='IP44 Version:  The shade is made of mouth-blown glass. The lamp base is made of a stamped sheet metal bracket with LEDs and a terminal- and lens cover in injection-molded ABS.  The IP44 ring is made of silicone and mounted on a stamped sheet metal cover.    With Inline Dimmer and plug version: The shade is made of mouth-blown glass. The lamp base is made of a stamped sheet metal bracket with LEDs and a terminal- and lens cover in injection-molded ABS. Cord with inline dimmer and plug-in injectio' WHERE name='Looped Wall/Ceiling Lamp';
UPDATE products SET dimensions='Height: 7,50 cm; Length: 51,50 cm; Width: 21,50 cm', materials='Made in ceramic stoneware with a high gloss glaze inside & out. The production process makes each bowl unique with small deviations in​ color, thickness and surface.' WHERE name='Mere Bowl';
UPDATE products SET dimensions='Height: 38,00 cm; Diameter: 90,00 cm', materials='Tabletop in marble. Marble is a metamorphic rock composed primarily of re-crystallized carbonate minerals, known for its natural veining and refined surface. With a timeless elegance, marble offers a unique and organic expression, making each piece one of a kind. Its smooth, cool touch enhances the tactile experience, while its durable nature ensures lasting beauty. Proper care helps preserve the marble’s integrity, maintaining its sophisticated appeal over time.   The table base is made of powd' WHERE name='Midst Coffee Table';
UPDATE products SET dimensions='Height: 73,50 cm; Length: 330,00 cm; Width: 140,00 cm', materials='The tabletop is available in lacquered MDF with black nanolaminate top or lacquered MDF with a linoleum top. Nanolaminate tabletops are made using FSC™-certified (FSC-C028824) wood. The table base is made of powder-coated steel with a protective rubber ring under it. Steel is an alloy of iron and carbon. Powder-coated steel has a subtle, textured expression and elegant feel while adding durability to the design and making it more corrosion- and chip-resistant.' WHERE name='Midst Conference Table';
UPDATE products SET dimensions='Height: 73,50 cm; Diameter: 120,00 cm', materials='The tabletop is available in lacquered MDF with a black nanolaminate top, lacquered MDF with a linoleum top, marble, or FSC™-certified (FSC-C028824) solid oak, treated with either a clear or dark oil. Nanolaminate tabletops are also made using FSC™-certified (FSC-C028824) wood. The table base is made of powder-coated steel with a protective rubber ring under it.  Table with stone tabletop: Please note that due to the natural variations in marble, each piece may differ slightly in pattern, color,' WHERE name='Midst Table';
UPDATE products SET dimensions='Length: 45,00 cm; Width: 45,00 cm', materials='Cushion cover: Textiles Ecriture/Hero from Kvadrat​ Inner sham: 55% polyester, 45% cotton​ Fill: 100% polyester' WHERE name='Mingle Cushion';
UPDATE products SET dimensions='Height: 16,60 cm; Width: 33,20 cm; Depth: 26,00 cm', materials='Modules in PU lacquered MDF or Oak veneered fiberboard. Clips are powder-coated bent steel with rubber inserts.  Lacquered versions: Every side is cut out of MDF, glued together, and painted with three layers of PU lacquer.  Oak versions: Every side is cut out of fiberboard with oak veneer and glued together.' WHERE name='Mini Stacked Storage System Brown Green - Medium';
UPDATE products SET dimensions='Height: 23,90 cm; Width: 49,80 cm; Depth: 26,00 cm', materials='Modules in PU lacquered MDF or Oak veneered fiberboard. Clips are powder-coated bent steel with rubber inserts.  Lacquered versions: Every side is cut out of MDF, glued together, and painted with three layers of PU lacquer.  Oak versions: Every side is cut out of fiberboard with oak veneer and glued together.' WHERE name='Mini Stacked Storage System Shelving - Configuration 8';
UPDATE products SET dimensions='Height: 79,00 cm; Length: 51,50 cm; Width: 45,50 cm; Depth: 51,50 cm; Seat height: 47,00 cm; Seat depth: 41,50 cm', materials='The back and seat of the Nerd Chair is made in form-pressed veneer alongside its legs in solid wood — both with a water-based lacquer. Glides in plastic.  Oak veneer and Stained Dark Brown: slight color variations can occur due to the inherent characteristics of the material.' WHERE name='Nerd Chair';
UPDATE products SET dimensions='Height: 45,00 cm; Length: 150,00 cm; Depth: 73,00 cm; Seat height: 45,00 cm; Seat depth: 73,00 cm', materials='The frame is made from steel and FSC™-certiﬁed (FSC-C028824) wood. The seat and back are constructed with molded PU foam and zig-zag springs for comfort and support. The piece is fully upholstered in textile, imitation leather, or leather, with leather sourced from selected premium suppliers. The legs are available in chromed or powder-coated steel and are fitted with felt glides.' WHERE name='Oslo Bench';
UPDATE products SET dimensions='Height: 75,50 cm; Width: 82,50 cm; Depth: 67,50 cm; Seat height: 40,00 cm; Seat depth: 54,00 cm', materials='The frame is made from steel and FSC™-certiﬁed (FSC-C028824) wood. The seat and back are constructed with molded PU foam and zig-zag springs for comfort and support. The piece is fully upholstered in textile, imitation leather, or leather, with leather sourced from selected premium suppliers. The legs are available in chromed or powder-coated steel and are fitted with felt glides.' WHERE name='Oslo Lounge Chair Swivel Base';
UPDATE products SET dimensions='Height: 75,50 cm; Width: 82,50 cm; Depth: 67,50 cm; Seat height: 40,00 cm; Seat depth: 54,00 cm', materials='The frame is made from steel and FSC™-certiﬁed (FSC-C028824) wood. The seat and back are constructed with molded PU foam and zig-zag springs for comfort and support. The piece is fully upholstered in textile, imitation leather, or leather, with leather sourced from selected premium suppliers. The legs are available in chromed or powder-coated steel and are fitted with felt glides.' WHERE name='Oslo Lounge Chair Tube Base';
UPDATE products SET dimensions='Height: 45,00 cm; Width: 100,00 cm; Depth: 73,00 cm; Seat height: 45,00 cm; Seat depth: 73,00 cm', materials='The frame is made from steel and FSC™-certiﬁed (FSC-C028824) wood. The seat and back are constructed with molded PU foam and zig-zag springs for comfort and support. The piece is fully upholstered in textile, imitation leather, or leather, with leather sourced from selected premium suppliers. The legs are available in chromed or powder-coated steel and are fitted with felt glides.' WHERE name='Oslo Pouf';
UPDATE products SET dimensions='Height: 80,50 cm; Width: 51,00 cm; Depth: 56,00 cm; Seat height: 48,00 cm', materials='The frame is made from steel and FSC™-certiﬁed (FSC-C028824) wood. The seat and back are constructed with molded PU foam and zig-zag springs for comfort and support. The piece is fully upholstered in textile, imitation leather, or leather, with leather sourced from selected premium suppliers. The legs are available in chromed or powder-coated steel and are fitted with felt glides.' WHERE name='Oslo Side Chair';
UPDATE products SET dimensions='Height: 79,50 cm; Width: 80,00 cm; Depth: 73,00 cm; Seat height: 45,00 cm; Seat depth: 54,00 cm', materials='The frame is made from steel and FSC™-certiﬁed (FSC-C028824) wood. The seat and back are constructed with molded PU foam and zig-zag springs for comfort and support. The piece is fully upholstered in textile, imitation leather, or leather, with leather sourced from selected premium suppliers. The legs are available in chromed or powder-coated steel and are fitted with felt glides.' WHERE name='Oslo Sofa 1-Seater';
UPDATE products SET dimensions='Height: 79,50 cm; Width: 150,00 cm; Depth: 73,00 cm; Seat height: 45,00 cm; Seat depth: 54,00 cm', materials='The frame is made from steel and FSC™-certiﬁed (FSC-C028824) wood. The seat and back are constructed with molded PU foam and zig-zag springs for comfort and support. The piece is fully upholstered in textile, imitation leather, or leather, with leather sourced from selected premium suppliers. The legs are available in chromed or powder-coated steel and are fitted with felt glides.' WHERE name='Oslo Sofa 2-Seater';
UPDATE products SET dimensions='Height: 79,50 cm; Width: 200,00 cm; Depth: 73,00 cm; Seat height: 45,00 cm; Seat depth: 54,00 cm', materials='The frame is made from steel and FSC™-certiﬁed (FSC-C028824) wood. The seat and back are constructed with molded PU foam and zig-zag springs for comfort and support. The piece is fully upholstered in textile, imitation leather, or leather, with leather sourced from selected premium suppliers. The legs are available in chromed or powder-coated steel and are fitted with felt glides.' WHERE name='Oslo Sofa 3-Seater';
UPDATE products SET dimensions='Height: 71,00 cm; Width: 88,00 cm; Depth: 84,00 cm; Seat height: 40,00 cm; Seat depth: 62,00 cm', materials='Base in powder coated or polished aluminum made using minimum 90% recycled die casted aluminum. The recycled die casted aluminum comes from a mix between post-industrial and post-consumer waste. Pre-mounted felt glides. Wood and steel construction. Cold foam filling. Fully upholstered with textile, imitation leather or leather. Leather from selected premium leather suppliers.' WHERE name='Outline Chair';
UPDATE products SET dimensions='Height: 40,00 cm; Width: 200,00 cm; Depth: 82,00 cm; Seat height: 40,00 cm; Seat depth: 82,00 cm', materials='Base in powder coated or polished aluminum made using minimum 90% recycled die casted aluminum. The recycled die casted aluminum comes from a mix between post-industrial and post-consumer waste. Pre-mounted felt glides. Wood and steel construction. Cold foam filling. Fully upholstered with textile, imitation leather or leather. Leather from selected premium leather suppliers.' WHERE name='Outline Daybed';
UPDATE products SET dimensions='Height: 30,00 cm; Width: 70,00 cm; Depth: 12,00 cm; Seat height: 40,00 cm', materials='Cold foam filling. Fully upholstered with textile, imitation leather or leather. Leather from selected premium leather suppliers.' WHERE name='Outline Daybed Cushion';
UPDATE products SET dimensions='Height: 40,00 cm; Width: 111,00 cm; Depth: 78,00 cm; Seat height: 40,00 cm; Seat depth: 78,00 cm', materials='Base in powder coated or polished aluminum made using minimum 90% recycled die casted aluminum. The recycled die casted aluminum comes from a mix between post-industrial and post-consumer waste. Pre-mounted felt glides. Wood and steel construction. Cold foam filling. Fully upholstered with textile, imitation leather or leather. Leather from selected premium leather suppliers.' WHERE name='Outline Pouf';
UPDATE products SET dimensions='Height: 71,00 cm; Width: 170,00 cm; Depth: 84,00 cm; Seat height: 40,00 cm; Seat depth: 62,00 cm', materials='Base in powder coated or polished aluminum made using minimum 90% recycled die casted aluminum. The recycled die casted aluminum comes from a mix between post-industrial and post-consumer waste. Pre-mounted felt glides. Wood and steel construction. Cold foam filling. Fully upholstered with textile, imitation leather or leather. Leather from selected premium leather suppliers.' WHERE name='Outline Sofa 2-Seater';
UPDATE products SET dimensions='Height: 71,00 cm; Width: 255,00 cm; Depth: 84,00 cm; Seat height: 40,00 cm; Seat depth: 62,00 cm', materials='Base in powder coated or polished aluminum made using minimum 90% recycled die casted aluminum. The recycled die casted aluminum comes from a mix between post-industrial and post-consumer waste. Pre-mounted felt glides. Wood and steel construction. Cold foam filling. Fully upholstered with textile, imitation leather or leather. Leather from selected premium leather suppliers.' WHERE name='Outline Sofa 3 1/2-Seater';
UPDATE products SET dimensions='Height: 71,00 cm; Width: 220,00 cm; Depth: 84,00 cm; Seat height: 40,00 cm; Seat depth: 62,00 cm', materials='Base in powder coated or polished aluminum made using minimum 90% recycled die casted aluminum. The recycled die casted aluminum comes from a mix between post-industrial and post-consumer waste. Pre-mounted felt glides. Wood and steel construction. Cold foam filling. Fully upholstered with textile, imitation leather or leather. Leather from selected premium leather suppliers.' WHERE name='Outline Sofa 3-Seater';
UPDATE products SET dimensions='Height: 71,00 cm; Width: 263,00 cm; Depth: 142,00 cm; Seat height: 40,00 cm; Seat depth: 122,00 cm', materials='Base in powder coated or polished aluminum made using minimum 90% recycled die casted aluminum. The recycled die casted aluminum comes from a mix between post-industrial and post-consumer waste. Pre-mounted felt glides. Wood and steel construction. Cold foam filling. Fully upholstered with textile, imitation leather or leather. Leather from selected premium leather suppliers.' WHERE name='Outline Sofa Chaise Longue';
UPDATE products SET dimensions='Height: 78,00 cm; Width: 220,00 cm; Depth: 84,00 cm; Seat height: 45,00 cm; Seat depth: 60,00 cm', materials='The seat and back frame are made using FSC™-certified (FSC-C028824) wood. The seat and back cushions are composed of PU foam and shredded foam with a wadding layer on top. The shredded foam is derived from production off-cuts that would otherwise be discarded. The armrest cushion is made from PU foam. The sofa is fully upholstered in textile, imitation leather, or leather, with leather sourced from selected premium suppliers. Pre-mounted felt glides are included. Loose cushions are available for' WHERE name='Outline Soft Sofa 3-Seater';
UPDATE products SET dimensions='Height: 11,00 cm; Width: 10,00 cm', materials='The candleholder is crafted from a single piece of extruded aluminum, shaped with precision. The candle holes and the edges are made and refined through CNC milling, and the surface is anodized for both durability and a sleek, matte finish.' WHERE name='Pair Candleholder';
UPDATE products SET dimensions='Height: 226,70 cm; Width: 57,00 cm; Depth: 20,90 cm', materials='Mirror-finish 84% recycled stainless steel.' WHERE name='Pleat Mirror';
UPDATE products SET dimensions='Length: 140,00 cm; Width: 85,00 cm', materials='Made using 100% recycled polyester. The recycled polyester comes from post-consumer waste.' WHERE name='Ply Rug / Recycled Polyester';
UPDATE products SET dimensions='Height: 45,20 cm', materials='Base in powder coated steel. Lighting unit in powder coated magnesium with silicone cord and opal diffuser. Cable drops in ABS with magnet. Power supply with ABS connector and PVC cord.' WHERE name='Post Table Lamp';
UPDATE products SET dimensions='Height: 0,40 cm', materials='Lighting unit in powder coated magnesium with silicone cord and opal diffuser. Wall mounting bracket in powder coated steel. Wall cable drops in ABS with magnet and repositionable adhesive tape. Power hub in wet painted ABS with PCV cord.' WHERE name='Post Wall Lamp';
UPDATE products SET dimensions='Height: 150,00 cm; Diameter: 31,50 cm; Cord length: 200,00 cm', materials='The Pull Floor Lamp is made in oiled oak wood or in grey lacquered oak wood with steel insert, textile covered plastic shade and black textile cord. The wood parts are handmade by manual lathe and wood carving machines. The shade is handcrafted and handled carefully through every step.' WHERE name='Pull Floor Lamp';
UPDATE products SET dimensions='Height: 36,00 cm; Width: 31,90 cm', materials='Made using 100% recycled plastic mixed with color additives. The recycled plastic comes from post-consumer waste.' WHERE name='Reduce Paper Bin';
UPDATE products SET dimensions='Height: 60,50 cm; Length: 56,20 cm; Width: 34,00 cm', materials='Tabletop in either Linoleum on MDF, oak laminate on MDF, oiled Solid Oak or oiled Smoked Oak. Frame in powder coated steel.' WHERE name='Relate Side Table';
UPDATE products SET dimensions='Length: 240,00 cm; Width: 170,00 cm', materials='Made from 100% New Zealand wool, hand-tufted in India. The backing is made of 100% cotton and pasted with synthetic latex, ensuring the rug lays smoothly on the floor. Shedding is a natural occurrence that will decrease over time. Please note that the color of the Relevo Rug may vary depending on the wool''s natural base color. Please note that all sizes of the Relevo Rug have a sizing tolerance of +/- 2%, meaning that the rug''s dimensions can differ by a maximum of 2%. Relevo does not require a ' WHERE name='Relevo Rug';
UPDATE products SET dimensions='Height: 73,00 cm; Length: 130,00 cm; Width: 120,00 cm; Seat height: 70,50 cm', materials='The tabletop and legs are made from plywood and finished with oak veneer, walnut veneer, or painted ash veneer, all treated with a water-based lacquer. Exposed plywood edges and bullnose details are stained to match the tabletop. As oak and walnut are natural materials, slight color variations may occur. The table includes a powder-coated steel mounting bracket and adjustable plastic glides. The table is made using FSC™-certified (FSC-C028824) wood and produced without intentionally adding PFAS.' WHERE name='Re-Norm Table';
UPDATE products SET dimensions='Height: 42,00 cm; Width: 100,00 cm; Depth: 80,00 cm; Seat height: 42,00 cm', materials='Legs are made in metal or FSC™-certified (FSC-C028824) wood. Frame in plywood and High-Density Fiberboard (HDF) made from FSC™-certified (FSC-C028824) wood, zig-zag springs, cold foam, and wadding. Upholstered in high-quality textiles.  EU/US version: Standard and high-resilience polyurethane foam.  UK version: Standard fire retardant polyurethane and combustion-modified high resilience foam.' WHERE name='Rest Pouf';
UPDATE products SET dimensions='Height: 72,00 cm; Width: 200,00 cm; Depth: 92,00 cm; Seat height: 42,00 cm; Seat depth: 60,00 cm', materials='Legs are made in metal or FSC™-certified (FSC-C028824) wood. Frame in plywood and High-Density Fiberboard (HDF) made from FSC™-certified (FSC-C028824) wood, zig-zag springs, cold foam, and wadding. Upholstered in high-quality textiles.  EU/US version: Standard and high-resilience polyurethane foam.  UK version: Standard fire retardant polyurethane and combustion-modified high resilience foam.' WHERE name='Rest Sofa 2-Seater';
UPDATE products SET dimensions='Height: 72,00 cm; Width: 260,00 cm; Depth: 92,00 cm; Seat height: 42,00 cm; Seat depth: 60,00 cm', materials='Legs are made in metal or FSC™-certified (FSC-C028824) wood. Frame in plywood and High-Density Fiberboard (HDF) made from FSC™-certified (FSC-C028824) wood, zig-zag springs, cold foam, and wadding. Upholstered in high-quality textiles.  EU/US version: Standard and high-resilience polyurethane foam.  UK version: Standard fire retardant polyurethane and combustion-modified high resilience foam.' WHERE name='Rest Sofa 3,5-Seater';
UPDATE products SET dimensions='Height: 13,00 cm; Length: 22,50 cm; Width: 15,00 cm; 5x130mm; 188x142x153mm; 267x195x240mm', materials='Liquid earthenware clay is poured into a plaster mold to form the design of the Ridge Planters. The planters are polished with a wet sponge and fired at 1000°C. After this initial firing, the inside is glazed with a glossy finish, while the outside is given a matte glaze. The planters are then fired again at 1100°C to complete the process.' WHERE name='Ridge Planter';
UPDATE products SET dimensions='Height: 28,00 cm; Diameter: 80,00 cm; Cord length: 400,00 cm', materials='The glass shade is mouth-blown and made with up to 75% recycled glass. The fixture includes user-replaceable G9 light sources with a CRI above 90. The suspension is made from die-cast and machined aluminum, supported by a steel aircraft wire. The cord and canopy are made from PVC and injection-molded ABS. The product is designed for disassembly and produced without intentionally added PFAS.' WHERE name='Rime Chandelier';
UPDATE products SET dimensions='Height: 23,00 cm; Length: 18,00 cm; Width: 110,00 cm; Cord length: 400,00 cm', materials='Mouth-blown glass shade. Suspension: Aluminum extruded profile with die-cast end pieces. Steel aircraft wire.' WHERE name='Rime Rail Lamp';
UPDATE products SET dimensions='Height: 16,20 cm; Length: 23,00 cm; Width: 12,00 cm; Cord length: 250,00 cm', materials='Mouth-blown glass shade. Wall bracket in aluminum, pressure die-casted and powder coated.  Wall bracket in steel and chrome plated. PVC cord.' WHERE name='Rime Wall Lamp';
UPDATE products SET dimensions='Height: 37,90 cm; Diameter: 34,00 cm; Cord length: 250,00 cm', materials='The lamp body and shade are in anodized aluminum. The underside of the shade is powder coated aluminum. Light can be controlled using the inline dimmer or rotating the lamp shade. Dimmable, integrated, and non-user replaceable LED light designed for Right to Repair means that only an electrician can replace the light source. Lumen: 800lm on 100% brightness. Lumen Maintenance (80%) : 50.000h. Kelvin: 2700K. CRI >90.' WHERE name='Set Table Lamp';
UPDATE products SET dimensions='Height: 35,00 cm; Width: 60,00 cm; Depth: 16,00 cm', materials='A single outdoor-suited foam core wrapped in wadding, enclosed in an inner lining, and finished with outdoor-suited upholstery.' WHERE name='Settle Cushion';
UPDATE products SET dimensions='Height: 86,50 cm; Width: 124,50 cm; Depth: 166,00 cm; Seat height: 42,00 cm; Seat depth: 126,00 cm', materials='Back cushion: The back cushion consists of a single outdoor-suited foam core wrapped in wadding and enclosed in an inner lining. It is finished with outdoor-suited upholstery. The Lounge Bed comes with two loose cushions for extra back support. Extra cushions can be purchased separately.  Seat cushion: The seat cushion is constructed from multiple layers of outdoor-suited foam to provide enhanced support and comfort. The foam is wrapped in wadding and an inner lining, and finished with outdoor-s' WHERE name='Settle Lounge Bed';
UPDATE products SET dimensions='Height: 73,00 cm; Width: 69,00 cm; Depth: 84,00 cm; Seat height: 44,00 cm; Seat depth: 55,00 cm', materials='Back cushion: The back cushion consists of a single outdoor-suited foam core wrapped in wadding and enclosed in an inner lining. It is finished with outdoor-suited upholstery. Loose cushions for added back support can be purchased separately.  Seat cushion: The seat cushion is constructed from multiple layers of outdoor-suited foam to provide enhanced support and comfort. The foam is wrapped in wadding and an inner lining, and finished with outdoor-suited upholstery. An integrated anti-slip feat' WHERE name='Settle Lounge Chair';
UPDATE products SET dimensions='Height: 73,00 cm; Width: 144,00 cm; Depth: 84,00 cm; Seat height: 44,00 cm; Seat depth: 55,00 cm', materials='Back cushion: The back cushion consists of a single outdoor-suited foam core wrapped in wadding and enclosed in an inner lining. It is finished with outdoor-suited upholstery. Loose cushions for added back support can be purchased separately.  Seat cushion: The seat cushion is constructed from multiple layers of outdoor-suited foam to provide enhanced support and comfort. The foam is wrapped in wadding and an inner lining, and finished with outdoor-suited upholstery. An integrated anti-slip feat' WHERE name='Settle Sofa 2-Seater';
UPDATE products SET dimensions='Height: 73,00 cm; Width: 201,00 cm; Depth: 84,00 cm; Seat height: 44,00 cm; Seat depth: 55,00 cm', materials='Back cushion: The back cushion consists of a single outdoor-suited foam core wrapped in wadding and enclosed in an inner lining. It is finished with outdoor-suited upholstery. Loose cushions for added back support can be purchased separately.  Seat cushion: The seat cushion is constructed from multiple layers of outdoor-suited foam to provide enhanced support and comfort. The foam is wrapped in wadding and an inner lining, and finished with outdoor-suited upholstery. An integrated anti-slip feat' WHERE name='Settle Sofa 3-Seater';
UPDATE products SET dimensions='Height: 13,40 cm; Diameter: 11,00 cm', materials='Mouth-blown glass, cut and polished.' WHERE name='Silent Vase';
UPDATE products SET dimensions='Height: 61,00 cm; Width: 44,00 cm; Depth: 35,00 cm', materials='Modules, plinths, and shelves are in PU lacquered MDF, oak, or walnut veneered fiberboard. The podium consists of a powder-coated steel frame and a wooden plate made from a PU lacquered MDF or oak/walnut veneered fiberboard. Clips are powder-coated bent steel with rubber inserts. Insert made from bent powder coated steel with rubber feet. Lacquered versions: Every side is cut out of MDF, glued together, and painted with three layers of PU lacquer. Oak and walnut versions: Every side is cut out o' WHERE name='Stacked Storage System Bedside Table - Brown Green - Configuration 2';
UPDATE products SET dimensions='Height: 228,00 cm; Width: 262,00 cm; Depth: 35,00 cm', materials='Modules, plinths, and shelves are in PU lacquered MDF, oak, or walnut veneered fiberboard. The podium consists of a powder-coated steel frame and a wooden plate made from a PU lacquered MDF or oak/walnut veneered fiberboard. Clips are powder-coated bent steel with rubber inserts. Insert made from bent powder coated steel with rubber feet. Lacquered versions: Every side is cut out of MDF, glued together, and painted with three layers of PU lacquer. Oak and walnut versions: Every side is cut out o' WHERE name='Stacked Storage System Bookcase - Oak - Configuration 8';
UPDATE products SET dimensions='Height: 119,00 cm; Width: 174,00 cm; Depth: 35,00 cm', materials='Modules, plinths, and shelves are in PU lacquered MDF, oak, or walnut veneered fiberboard. The podium consists of a powder-coated steel frame and a wooden plate made from a PU lacquered MDF or oak/walnut veneered fiberboard. Clips are powder-coated bent steel with rubber inserts. Insert made from bent powder coated steel with rubber feet. Lacquered versions: Every side is cut out of MDF, glued together, and painted with three layers of PU lacquer. Oak and walnut versions: Every side is cut out o' WHERE name='Stacked Storage System Hallway Storage - Oak - Configuration 4';
UPDATE products SET dimensions='Height: 228,00 cm; Width: 262,00 cm; Depth: 35,00 cm', materials='Modules, plinths, and shelves are in PU lacquered MDF, oak, or walnut veneered fiberboard. The podium consists of a powder-coated steel frame and a wooden plate made from a PU lacquered MDF or oak/walnut veneered fiberboard. Clips are powder-coated bent steel with rubber inserts. Insert made from bent powder coated steel with rubber feet. Lacquered versions: Every side is cut out of MDF, glued together, and painted with three layers of PU lacquer. Oak and walnut versions: Every side is cut out o' WHERE name='Stacked Storage System Office Storage - Grey - Configuration 5';
UPDATE products SET dimensions='Height: 121,00 cm; Width: 262,00 cm; Depth: 35,00 cm', materials='Modules, plinths, and shelves are in PU lacquered MDF, oak, or walnut veneered fiberboard. The podium consists of a powder-coated steel frame and a wooden plate made from a PU lacquered MDF or oak/walnut veneered fiberboard. Clips are powder-coated bent steel with rubber inserts. Insert made from bent powder coated steel with rubber feet. Lacquered versions: Every side is cut out of MDF, glued together, and painted with three layers of PU lacquer. Oak and walnut versions: Every side is cut out o' WHERE name='Stacked Storage System Sideboard - Brown Green - Configuration 4';
UPDATE products SET dimensions='Height: 36,40 cm; Diameter: 45,00 cm; Cord length: 500,00 cm', materials='The Strand Pendant Lamp is made of a cocoon layer with an inner steel structure, a PVC cord and PVC covered steel wire.' WHERE name='Strand Pendant Lamp White - Open - Open - Ø 60 cm';
UPDATE products SET dimensions='Height: 39,00 cm; Diameter: 29,00 cm; Cord length: 250,00 cm', materials='Cocoon layer with inner steel structure, base in iron and aluminum, PVC cord with inline dimmer. Cocoon Resin. A cocoon composite material that is sprayed onto a steel frame through a 3-step process of the fiber web, cocoon plastic, and protective top coating.' WHERE name='Strand Table Lamp White - H 59 cm';
UPDATE products SET dimensions='Height: 45,00 cm; Width: 45,00 cm', materials='Textile in 100% wool. Filling is a mix of feather and polyester. The weaving process is specially developed for the Tiles Cushion in cooperation between Gudbrandsdalen, Anderssen & Voll and Muuto. Using a colored double-weaving on top of a black bottom layered weaving and binding down the three colors, nuances are made in the textile.' WHERE name='Tile Cushion';
UPDATE products SET dimensions='Height: 40,00 cm; Width: 16,00 cm; Depth: 29,50 cm; Cord length: 250,00 cm', materials='Made in casted and extruded aluminum. PVC cord.' WHERE name='Tip Table Lamp';
UPDATE products SET dimensions='Height: 13,00 cm; Diameter: 21,00 cm; Cord length: 400,00 cm', materials='Spun steel shade with a high gloss wet paint finish. PVC cord. Socket in nylon. GX53 light bulb included. Canopy in ABS is included. Cord length 400cm / 157.5“' WHERE name='Top Pendant Lamp';
UPDATE products SET dimensions='Height: 40,00 cm; Width: 60,00 cm', materials='The pillow case is made from 100% baby llama wool, the inner sham is 100% cotton and the filling consists of 50% feather and 50% polyfiber.  The front of the pillow case is hand-knitted with a characteristic pearl knit structure. Back in one-color knit, knitted on a 14-gage machine in 2/24 x 1 ply yarn.' WHERE name='Twine Cushion';
UPDATE products SET dimensions='Height: 51,50 cm; Diameter: 37,50 cm; Cord length: 350,00 cm', materials='Mouth-blown glass shade, deep drawn and punched metal mesh, spun suspension cap, steel pendant tube.  Injection molded diffuser and canopy.' WHERE name='Two-Layer Pendant Lamp';
UPDATE products SET dimensions='Height: 31,00 cm; Diameter: 55,00 cm; Cord length: 500,00 cm', materials='The shade is made using 49% recycled plastic. The recycled plastic comes from post-consumer waste. Rubber cord.' WHERE name='Under The Bell Pendant Lamp';
UPDATE products SET dimensions='Height: 29,50 cm; Diameter: 32,50 cm; Cord length: 350,00 cm', materials='The shade is made of silicone rubber, and the cord is made of PVC. The diffuser is made of clear frosted opal acrylic. The shade is formed through injection-molded liquid rubber under high temperatures. The diffuser and socket holder are cut by laser.Silicone rubber is made from silicone elastomers, and it is created with extensive flexibility, durability, strength, and a specifically calibrated translucency.' WHERE name='Unfold Pendant Lamp';
UPDATE products SET dimensions='Length: 240,00 cm; Width: 170,00 cm', materials='The Varjo Rug is made in 100% New Zealand lambswool. The wool is dyed and the rug is woven by hand.' WHERE name='Varjo Rug';
UPDATE products SET dimensions='Height: 78,50 cm; Width: 53,00 cm; Depth: 50,00 cm; Seat height: 45,00 cm; Seat depth: 41,00 cm', materials='Non-upholstered version: The shell is made from form-pressed oak or ash veneer with water-based lacquer. Upholstered version: The shell is made from form-pressed oak or ash veneer with foam and fully upholstered with high-quality textile or leather.  Sled base in powder-coated steel.' WHERE name='Visu Chair Sled Base';
UPDATE products SET dimensions='Height: 81,00 cm; Width: 55,00 cm; Depth: 52,50 cm; Seat height: 47,00 cm; Seat depth: 41,00 cm', materials='Non-upholstered version: The shell is made from form-pressed oak or ash veneer with water-based lacquer. Upholstered version: The shell is made from form-pressed oak or ash veneer with foam and fully upholstered with high-quality textile or leather.  Tube base in powder-coated steel.' WHERE name='Visu Chair Tube Base';
UPDATE products SET dimensions='Height: 80,00 cm; Width: 46,00 cm; Depth: 50,00 cm; Seat height: 46,00 cm; Seat depth: 41,00 cm', materials='Non-upholstered version: The shell is made from form-pressed oak or ash veneer with water-based lacquer. Upholstered version: The shell is made from form-pressed oak or ash veneer with foam and fully upholstered with high-quality textile or leather.  Wood Base is made of form-pressed oak or ash veneer with water-based lacquer.  Oak and ash veneer: slight color variations can occur due to the material''s inherent characteristics.  Lacquered Ash Veneer: Ash is a key material in Scandinavian furnitu' WHERE name='Visu Chair Wood Base';
UPDATE products SET dimensions='Height: 78,50 cm; Width: 50,00 cm; Depth: 55,50 cm; Seat height: 46,00 cm; Seat depth: 43,00 cm', materials='Non-upholstered version: The shell is made from form-pressed oak or ash veneer with water-based lacquer.  Upholstered version: The shell is made from form-pressed oak or ash veneer with foam and fully upholstered with high-quality textile or leather.  Swivel Base & Swivel Base w. Return: Swivel Base in die casted aluminum. The swivel foot is cast in one piece.' WHERE name='Visu Wide Chair Swivel Base';
UPDATE products SET dimensions='Height: 78,50 cm; Width: 50,00 cm; Depth: 55,50 cm; Seat height: 46,00 cm; Seat depth: 43,00 cm', materials='Non-upholstered version: The shell is made from form-pressed oak or ash veneer with water-based lacquer.  Upholstered version: The shell is made from form-pressed oak or ash veneer with foam and fully upholstered with high-quality textile or leather.  Wood Base in form-pressed oak or ash veneer with water-based lacquer.' WHERE name='Visu Wide Chair Wood Base';
UPDATE products SET dimensions='Height: 4,00 cm; Diameter: 50,00 cm', materials='The Wave Tray is made in 100% stainless steel' WHERE name='Wave Tray';
UPDATE products SET dimensions='Height: 79,60 cm; Width: 90,80 cm; Depth: 46,30 cm; Seat height: 45,00 cm; Seat depth: 38,90 cm', materials='The Workshop Bench is made using traditional techniques that emphasize workmanship and detailing. Frame and legs in solid oak, seat and back in form pressed oak veneer — all parts in FSC™-certified wood (FSC-C028824) and coated with a water-based lacquer. Plastic glides. Oak veneer: slight color variations may occur due to the inherent characteristics of the material.' WHERE name='Workshop Bench';
UPDATE products SET dimensions='Height: 79,20 cm; Width: 39,80 cm; Depth: 46,30 cm; Seat height: 45,00 cm; Seat depth: 38,90 cm', materials='The Workshop Chair is made with traditional techniques that places emphasis on workmanship and detailing. Frame and legs in solid wood, seat and back in shape pressed layer glued veneer.  Oak and Black: Seat and back in oak veneer while frame and legs are made in solid oak — all parts in a water-based lacquer. Oak veneer: slight color variations can occur due to the inherent characteristics of the material.' WHERE name='Workshop Chair';
UPDATE products SET dimensions='Height: 73,00 cm; Length: 130,00 cm; Width: 65,00 cm; Seat height: 65,00 cm', materials='Frame and legs are made from lacquered solid oak. Black version comes in lacquered oak. Oak version comes with a matte clear lacquer. Table top with a lacquered oak veneer or linoleum finish.  Oak veneer: slight color variations can occur due to the inherent characteristics of the material.' WHERE name='Workshop Table';
UPDATE products SET dimensions='Height: 81,50 cm; Width: 91,30 cm; Depth: 91,00 cm; Seat height: 44,50 cm; Seat depth: 54,00 cm', materials='Seat made of pressed felt with steel reinforcement. Wrap Lounge Chair’s shell is clad with multiple layers of foam and wadding and finished with textile upholstery. Upholstered in high-quality textiles from Kvadrat and Rohleder. ​Tube base in powder coated steel with plastic gliders. ​' WHERE name='Wrap Lounge Chair';

-- Summary: 191 matched, 20 unmatched

-- Products NOT found in dev DB (need separate scraping):
--   70/70 Outdoor Table  [https://www.muuto.com/product/70-70-Outdoor-Table--p114146/p114146/]
--   Adjustable Feet  [https://www.muuto.com/product/Adjustable-Feet--p33182/p33182/]
--   Ceiling Cap  [https://www.muuto.com/product/Ceiling-Cap--p33155/p33155/]
--   Compile Shelving System Essential Pack  [https://www.muuto.com/product/Compile-Shelving-System-Essential-Pack-p48437/p48437/]
--   Connect Modular Sofa 3-Seater - Configuration 4 - Acca 731  [https://www.muuto.com/product/Connect-Modular-Sofa-3-Seater-p19382/x133007/]
--   Connect Modular Sofa 6-Seater  [https://www.muuto.com/product/Connect-Modular-Sofa-6-Seater-p133301/p133301/]
--   Cover and Visu Chair Transport Trolley  [https://www.muuto.com/product/Transport-Trolley--COVTRO/COVTRO01/]
--   Fiber Chair Seat Pad  [https://www.muuto.com/product/Fiber-Chair-Seat-Pad--p33207/p33207/]
--   Fiber Lounge Chair Seat Pad  [https://www.muuto.com/product/Fiber-Lounge-Chair-Seat-Pad--p33208/p33208/]
--   Linear Steel Chair/Lounge Chair Seat Pad  [https://www.muuto.com/product/Linear-Steel-Lounge-Chair-Seat-Pad/]
--   Linear Steel Cover Outdoor Cover for Linear Steel Table 140 x 75 CM / 55.1 x 29.5 - 140 x 75 cm  [https://www.muuto.com/product/Linear-Steel-Cover--p24950/30976/]
--   Linear System Cable Tray  [https://www.muuto.com/product/Linear-System-Cable-Tray--p32124/p32124/]
--   Linear System Power Configuration  [https://www.muuto.com/product/Linear-System-Power-Configuration--p32128/p32128/]
--   Linear System Power Starter Kit  [https://www.muuto.com/product/Linear-System-Power-Starter-Kit--p90713/p90713/]
--   Linear System Table Power Outlet  [https://www.muuto.com/product/Linear-System-Table-Power-Outlet--p32117/p32117/]
--   Midst Power Units  [https://www.muuto.com/product/Power-Units--PWCENCFG/PWCENCFGUS01V1/]
--   Portable Lamp Charging Station  [https://www.muuto.com/product/Lamp-Charging-Station--PLCSEU/PLCSEU01/]
--   Power Extension Kit  [https://www.muuto.com/product/Power-Extension-Kit--p32009/p32009/]
--   The Dots Metal  [https://www.muuto.com/product/Dots-Metal--p1815/p1815/]
--   Tub Jug  [https://www.muuto.com/product/Tub-Jug--p2216/p2216/]